#!/usr/bin/env python3
"""Prepare or verify input datasets for CUDA-Hercules Class 3 tasks."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TASK_ROOT = ROOT / "tasks" / "class3"


@dataclass(frozen=True)
class DatasetTask:
    name: str
    required: tuple[str, ...] = ()
    prepare_cmds: tuple[tuple[str, ...], ...] = ()
    large_download: bool = False
    notes: str = ""
    env: dict[str, str] = field(default_factory=dict)


TASKS: dict[str, DatasetTask] = {
    "cuszp": DatasetTask(
        "cuszp",
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Uses synthetic benchmark inputs generated by the harness; no dataset staging needed.",
    ),
    "exachem_ccsd_t": DatasetTask(
        "exachem_ccsd_t",
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Uses built-in deterministic benchmark tensors; no external dataset staging needed.",
    ),
    "gpumd": DatasetTask(
        "gpumd",
        required=(
            "gpumd/data/Ar_256000.xyz",
            "gpumd/data/Ar_500000.xyz",
            "gpumd/data/Si_27000.xyz",
            "gpumd/data/Si_64000.xyz",
            "gpumd/data/NaCl_8000.xyz",
            "gpumd/data/NaCl_32768.xyz",
            "gpumd/data/ref_forces/lj_Ar_256000.bin",
            "gpumd/data/ref_forces/lj_Ar_500000.bin",
            "gpumd/data/ref_forces/tersoff_Si_27000.bin",
            "gpumd/data/ref_forces/tersoff_Si_64000.bin",
            "gpumd/data/ref_forces/coulomb_NaCl_8000.bin",
            "gpumd/data/ref_forces/coulomb_NaCl_32768.bin",
            "gpumd/.blackbox_inputs_v1/workloads.json",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Generates .blackbox_inputs_v1 standardized workloads from included xyz/ref_force files.",
    ),
    "icicle_zk": DatasetTask(
        "icicle_zk",
        required=(
            "icicle_zk/ref_data/ntt_24.bin",
            "icicle_zk/ref_data/msm_points_22.bin",
            "icicle_zk/ref_data/msm_scalars_22.bin",
            "icicle_zk/cuda_backend/cuda/libicicle_backend_cuda_device.so",
            "icicle_zk/cuda_backend/bn254/cuda/libicicle_backend_cuda_curve_bn254.so",
            "icicle_zk/cuda_backend/bn254/cuda/libicicle_backend_cuda_field_bn254.so",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Reference data and Icicle CUDA backend libraries are included in this release.",
    ),
    "liberator": DatasetTask(
        "liberator",
        required=(
            "liberator/data/friendster.bcsr",
            "liberator/data/friendster.bcsc",
            "liberator/data/friendster.bwcsr",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        large_download=True,
        notes="Downloads SNAP Friendster and converts it. Requires about 90 GB free disk.",
    ),
    "llmc": DatasetTask(
        "llmc",
        required=(
            "llmc/data/tiny_shakespeare_train.bin",
            "llmc/data/tiny_shakespeare_val.bin",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Downloads TinyShakespeare and tokenizes with tiktoken if bins are missing.",
    ),
    "mgg_agnn": DatasetTask(
        "mgg_agnn",
        required=("tcgnn_gcn/data/amazon0505.npz",),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Shares the amazon0505 graph staged by tcgnn_gcn.",
    ),
    "mgg_gcn": DatasetTask(
        "mgg_gcn",
        required=(
            "mgg_gcn/data/bin/paper100M_beg_pos.bin",
            "mgg_gcn/data/bin/paper100M_csr.bin",
            "mgg_gcn/data/bin/paper100M_weight.bin",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        large_download=True,
        notes="Downloads ogbn-papers100M via OGB and converts to MGG CSR. Requires tens of GB.",
    ),
    "parafrost_sat": DatasetTask(
        "parafrost_sat",
        required=(
            "parafrost_sat/data/ps_300_311_20.cnf",
            "parafrost_sat/data/sokoban-p01.sas.ex.17.cnf",
            "parafrost_sat/data/manol-pipe-c7nidw.cnf",
            "parafrost_sat/data/ps_200_301_70.cnf",
            "parafrost_sat/data/abw-N-bcsstk07.mtx-w44.cnf",
            "parafrost_sat/data/Mickey_out250_known_last146_0.cnf",
            "parafrost_sat/data/gaussian.c.75.smt2-cvc4.cnf",
            "parafrost_sat/data/Mickey_out250_known_last147_0_u.cnf",
            "parafrost_sat/data/sv-comp19_prop-reachsafety.barrier_3t_true-unreach-call.i-witness.cnf",
            "parafrost_sat/data/T124.2.1.cnf",
            "parafrost_sat/.blackbox_inputs_v1/instances.json",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Creates .blackbox_inputs_v1 symlinks/manifest from the included 10 CNF files.",
    ),
    "tcgnn_gcn": DatasetTask(
        "tcgnn_gcn",
        required=(
            "tcgnn_gcn/data/amazon0505.npz",
            "tcgnn_gcn/data/artist.npz",
            "tcgnn_gcn/data/soc-BlogCatalog.npz",
            "tcgnn_gcn/data/amazon0601.npz",
        ),
        prepare_cmds=(("bash", "prepare_data.sh"),),
        notes="Downloads TC-GNN graph npz files if missing.",
    ),
}


def _exists(rel: str) -> bool:
    path = TASK_ROOT / rel
    return path.exists() and path.stat().st_size > 0


def _missing(task: DatasetTask) -> list[str]:
    return [rel for rel in task.required if not _exists(rel)]


def _run(task: DatasetTask, cmd: tuple[str, ...]) -> None:
    workdir = TASK_ROOT / task.name
    env = os.environ.copy()
    env.update(task.env)
    print(f"  $ {' '.join(cmd)}  (cwd={workdir.relative_to(ROOT)})", flush=True)
    subprocess.check_call(list(cmd), cwd=workdir, env=env)


def _parse_tasks(raw: list[str]) -> list[str]:
    if not raw or raw == ["all"]:
        return list(TASKS)
    out: list[str] = []
    for item in raw:
        for name in item.split(","):
            name = name.strip()
            if name:
                out.append(name)
    unknown = sorted(set(out) - set(TASKS))
    if unknown:
        raise SystemExit(f"Unknown Class 3 task(s): {', '.join(unknown)}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tasks",
        nargs="*",
        default=["all"],
        help="Task names or comma-separated names. Default: all.",
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Only check required files; do not run preparation commands.",
    )
    parser.add_argument(
        "--include-large-downloads",
        action="store_true",
        help="Allow dataset preparation and strict verification for inputs that may download tens of GB.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print a JSON summary in addition to human-readable output.",
    )
    args = parser.parse_args()

    selected = _parse_tasks(args.tasks)
    summary: dict[str, dict[str, object]] = {}
    failed = False

    for name in selected:
        task = TASKS[name]
        print(f"\n== {name} ==")
        if task.notes:
            print(f"  {task.notes}")

        missing_before = _missing(task)
        skipped = False

        if missing_before and task.large_download and not args.include_large_downloads:
            skipped = True
            print("  Missing required files:")
            for rel in missing_before:
                print(f"    - tasks/class3/{rel}")
            print("  Skipped preparation because this task requires a large external download.")
            print("  Re-run with --include-large-downloads to prepare it.")
        elif not args.verify_only and task.prepare_cmds:
            for cmd in task.prepare_cmds:
                _run(task, cmd)

        missing_after = _missing(task)
        if missing_after and not skipped:
            failed = True
            label = "MISSING" if args.verify_only else "MISSING after preparation"
            print(f"  {label}:")
            for rel in missing_after:
                print(f"    - tasks/class3/{rel}")
        elif not missing_after:
            print("  OK")
        elif not task.required:
            print("  OK")

        summary[name] = {
            "ok": not missing_after,
            "missing": missing_after,
            "large_download": task.large_download,
            "skipped": skipped,
        }

    if args.json:
        print("\n" + json.dumps(summary, indent=2))

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
